version: "3.9"

services:
  web:
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      #　consider nginx port
      - 80:80
      - 443:443
    volumes:
      - ./zend/public:/var/www/zend/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/ssl/certs

  app:
    build:
      context: ./docker/php
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: tutorial
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - ./docker/php/php.ini:/usr/ocal/etc/php/php.ini
      - ./zend:/var/www/zend

  db:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: tutorial
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

volumes:
  data:
    driver: local
